// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zaufbheimbpqzfovfrpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphdWZiaGVpbWJwcXpmb3ZmcnBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMTMxMTcsImV4cCI6MjA2ODU4OTExN30.DY6tjYlLqp1DzLm_aHC_-XKI1h-E42-dL46Z8YqLOGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});